import Header from "@/components/atoms/Header";
import MainWrapper from "@/components/molecules/MainWapper";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full h-full">
      <body className={`${inter.className} bg-white w-full h-full`}>
        <SessionProvider>
          <Header />
          <main className="h-[calc(100%-150px)] w-full px-[30px] pt-4">
            {/* @ts-expect-error Async Server Component */}
            <MainWrapper>{children}</MainWrapper>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
